language: node_js
node_js:
  - node # latest stable Node.js release
  - lts/* # latest LTS Node.js release
  - 15 # latest 15.x release
  - 14 # latest 14.x release
  - 12 # latest 12.x release
  - 10 # latest 10.x release


os:
  - linux

install:
  - npm install

cache:
  directories:
    - 'node_modules'

script:
  - npm run coverage

notifications:
  email: false
